services:
  ocr:
    build:
      context: .
      dockerfile: ocr/Dockerfile
    networks:
      - app-net
    volumes:
      - ./ocr/input:/app/input
      - ./ocr/output:/app/output

  translate:
    build:
      context: .
      dockerfile: translate/Dockerfile
    stdin_open: true
    tty: true
    networks:
      - app-net
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
    volumes:
      - gcloud-config:/root/.config/gcloud
    command: |
      bash -c "
        echo 'Fetching access token...' &&
        GCP_ACCESS_TOKEN=$$(gcloud auth application-default print-access-token) translate
      "
    healthcheck:
      test: >
        bash -c "
          curl \
            -H \"Authorization: Bearer $$(gcloud auth application-default print-access-token)\" \
            -H \"x-goog-user-project: $$GCP_PROJECT_ID\" \
            -H \"Content-Type: application/json\" \
            https://translation.googleapis.com/language/translate/v2 \
            -d '{\"q\":\"Hello\",\"target\":\"es\"}'
        "
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

  translate-login:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli
    networks:
      - app-net
    volumes:
      - gcloud-config:/root/.config/gcloud
    stdin_open: true
    tty: true
    command: gcloud auth application-default login

  tts:
    build:
      context: .
      dockerfile: tts/Dockerfile
    networks:
      - app-net
    volumes:
      - ./tts/model:/app/tts/model
      - ./tts/sherpa-onnx:/app/tts/sherpa-onnx

networks:
  app-net:
    driver: bridge

volumes:
  gcloud-config: