services:
#  google-cloud-cli:
#    image: gcr.io/google.com/cloudsdktool/google-cloud-cli
#    networks:
#      - app-net
#    volumes:
#      - .:/app
#    working_dir: /app
#    command: gcloud init && gcloud auth application-default login

  translate:
    image: golang:tip-trixie
    networks:
      - app-net
    environment:
      - GCP_ACCESS_TOKEN=${GCP_ACCESS_TOKEN}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./translate/
    healthcheck:
      test: |
        curl \
          -H "Authorization: Bearer $$GCP_ACCESS_TOKEN" \
          -H "x-goog-user-project: $$GCP_PROJECT_ID" \
          -H "Content-Type: application/json" \
          https://translation.googleapis.com/language/translate/v2 \
          -d '{"q":"Hello","target":"es"}'
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
#    depends_on:
#      google-cloud-cli:
#        condition: service_completed_successfully

networks:
  app-net:
    driver: bridge
